### PR TITLE
[Audit] Filter `debugDatastoreMapMutation` mutations

### PR DESCRIPTION
**Pull request by dat-boris**
## Summary:
We are getting noise from the DOS alert with this route.
Adding to safelist for now.

Issue: https://khanacademy.slack.com/archives/C8XGW76FQ/p1633384347494400?thread_ts=1633383959.494200&cid=C8XGW76FQ

## Test plan:

Deploy and 🤞

### CODE REVIEW

**Review by LoveAndCoding — APPROVED** [review]
LGTM

**Comment by LoveAndCoding** [comment]
We should also clean up that variable name so it aligns with ADR-365 (maybe `safelist`?)

**Comment by dat-boris** [comment]
Ah good point! I miss that one - I will bear in mind to fix that when we next update

**Comment by latteier** [comment]
Thanks!

**Pull request merged**
